### ISSUE TITLE
Crashed when parse a video which in chinese directory name or include chinese chars video name 

### ISSUE THREAD

**Issue by leogitpro** [sbraz/pymediainfo#121]
Hi, I use pymediainfo to extract the information for video.
In the development mode. everyting is fine.
But when made a application from pyinstaller. when the program read a video file from pure english path will be OK.
if the path include chinese chars will be crashed. like: /Users/leo/Movies/测试视频/test01.mp4, or /Users/leo/Movies/测试01.mp4.
But the same file copy to /Users/leo/Movies/test01.mp4 will be parsed success.
Is there a encode bug?

**Comment by sbraz** [comment]
Hello, that looks like a bug with pyinstaller. Please provide at least a stack trace so I can see what is happening.

**Comment by leogitpro** [comment]
Hi @sbraz , I try to use ffmpeg instead pymediainfo to get the video info in my app. It's works well.
Anyway, I have attached a creash report in the attchments.
Thanks a lot!
[pymediainfo_crash.txt](https://github.com/sbraz/pymediainfo/files/8598609/pymediainfo_crash.txt)
.

**Comment by rsnyman** [comment]
Hrm, I'm seeing a similar issue. Some of my app's users (macOS, PyInstaller) are reporting something similar (tracebacks below). I cannot reproduce on Linux, but I'll try on macOS.

```
Traceback (most recent call last):
  File "openlp/core/lib/mediamanageritem.py", line 602, in on_add_click
  File "openlp/core/lib/mediamanageritem.py", line 623, in add_to_service
  File "openlp/core/lib/mediamanageritem.py", line 663, in build_service_item
  File "openlp/plugins/media/lib/mediaitem.py", line 294, in generate_slide_data
  File "openlp/core/ui/media/mediacontroller.py", line 348, in media_length
  File "pymediainfo/__init__.py", line 496, in parse
RuntimeError: An error occured while opening /Users/user/Te daré lo mejor - Jesús Adrian Romero [Con letra].mp4 with libmediainfo
```

```
Traceback (most recent call last):
  File "openlp/core/lib/mediamanageritem.py", line 505, in on_double_clicked
  File "openlp/core/lib/mediamanageritem.py", line 528, in on_preview_click
  File "openlp/core/lib/mediamanageritem.py", line 663, in build_service_item
  File "openlp/plugins/media/lib/mediaitem.py", line 294, in generate_slide_data
  File "openlp/core/ui/media/mediacontroller.py", line 348, in media_length
  File "pymediainfo/__init__.py", line 496, in parse
RuntimeError: An error occured while opening /Users/user/Åsnan & Kossan dansar till ”Jag går på livets väg” av Sofia och Hanna Corneskog.mp4 with libmediainfo
```

**Comment by sbraz** [comment]
@rsnyman Hi, I really don't know what could happen with PyInstaller. I don't have an OSX system I can test right now. If you could reproduce, it would be nice. I assume, outside of PyInstaller, there won't be a problem.

@JulienPalard is there any way we could debug the fact that `lib.MediaInfo_Open` returns `0`? Maybe a debug option?

**Comment by sbraz** [comment]
@rsnyman any luck reproducing without PyInstaller? If I were to attempt to reproduce this *with* PyInstaller, how would I do it?

**Comment by maxlund** [comment]
I believe the issue here is that PyInstaller doesn't set UTF-8 locale by default, and does not inherit the system locale. I added a runtime hook like this, which runs before everything else on startup of the PyInstaller binary:
```
import locale
import os
import sys


def _in_ascii_locale() -> bool:
    # Returns True when LC_CTYPE is 'C', 'POSIX', ''  ( = ASCII )
    return locale.setlocale(locale.LC_CTYPE, None) in (None, "", "C", "POSIX")


if _in_ascii_locale():
    if sys.platform == "darwin":
        target = "en_US.UTF-8"  # macOS locale string
    elif os.name == "nt":
        target = ".UTF-8"  # Windows CRT "code page 65001"
    else:
        target = "en_US.UTF-8"

    os.environ["LC_ALL"] = target
    os.environ["LANG"] = target
    try:
        locale.setlocale(locale.LC_ALL, target)  # flips the whole C runtime
    except locale.Error:
        # last-resort: turn on Python’s UTF-8 mode and re-exec
        os.environ["PYTHONUTF8"] = "1"
        os.execv(sys.executable, [sys.executable, *sys.argv])
```
