### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by jtara1** [sbraz/pymediainfo#42]
I was using this module a month ago, idk what changed.

I'm running the demo.py

pymediainfo (2.2.0)
python 3.6.0
Win10

```
C:\Python36\python.exe C:/Users/James/Documents/_Github-Projects/MediaToVideo/MediaToVideo/GetMediaFiles/demo.py C:\Users\James\Pictures\pic.PNG
Traceback (most recent call last):
  File "C:/Users/James/Documents/_Github-Projects/MediaToVideo/MediaToVideo/GetMediaFiles/demo.py", line 44, in <module>
    process(sys.argv[1])
  File "C:/Users/James/Documents/_Github-Projects/MediaToVideo/MediaToVideo/GetMediaFiles/demo.py", line 25, in process
    media_info = MediaInfo.parse(fname)
  File "C:\Python36\lib\site-packages\pymediainfo\__init__.py", line 176, in parse
    lib = cls._get_library(library_file)
  File "C:\Python36\lib\site-packages\pymediainfo\__init__.py", line 142, in _get_library
    return windll.MediaInfo
  File "C:\Python36\lib\ctypes\__init__.py", line 414, in __getattr__
    dll = self._dlltype(name)
  File "C:\Python36\lib\ctypes\__init__.py", line 344, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

**Comment by sbraz** [comment]
Probably the DLL Location, it has to be in System32 or the current folder. If it is not, try passing its path to the `parse` method through the `library_path` parameter:
https://pymediainfo.readthedocs.io/en/latest/pymediainfo.html#pymediainfo.MediaInfo.parse

**Comment by jtara1** [comment]
Ok, thanks, didn't see that param, mb.

Fixed with 

```
    try:
        media_info = MediaInfo.parse(fname)
    except OSError:
        media_info = MediaInfo.parse(
            fname,
            library_file="C:\\Program Files\\MediaInfo\\MediaInfo.dll"
        )
```

which assumes the location of the dll (default install dir for windows).
Using a try block just b/c it should still work on linux unless I also get an OSError there.
