### ISSUE TITLE
KeyError: 'type' occurs when handling some flv files

### ISSUE THREAD

**Issue by choyj** [sbraz/pymediainfo#55]
In a few flv files, when attempting to get tracks in the following code:
```
        m = MediaInfo.parse(filename)
        print(len(m.tracks))
```

I get the following exception:
```
Traceback (most recent call last):
  File "/mnt/d/ff/get_duration.py", line 20, in <module>
    get_duration('/mnt/z/bad_b1.flv')
  File "/mnt/d/ff/get_duration.py", line 6, in get_duration
    print(len(m.tracks))
  File "/usr/local/lib/python3.6/dist-packages/pymediainfo/__init__.py", line 258, in tracks
    self._populate_tracks()
  File "/usr/local/lib/python3.6/dist-packages/pymediainfo/__init__.py", line 241, in _populate_tracks
    self._tracks.append(Track(xml_track))
  File "/usr/local/lib/python3.6/dist-packages/pymediainfo/__init__.py", line 58, in __init__
    self.track_type = xml_dom_fragment.attrib['type']
KeyError: 'type'
```

My environment is Ubuntu 18.04 running in a WSL on Windows 10 using Python 3 and pymediainfo 2.3.0

I've attached two example xml files with this problem.
[bad_b1.txt](https://github.com/sbraz/pymediainfo/files/2321312/bad_b1.txt)
[bad_b2.txt](https://github.com/sbraz/pymediainfo/files/2321313/bad_b2.txt)

**Comment by sbraz** [comment]
Same here, please upload a sample file.

**Comment by choyj** [comment]
I didn't want to send up the files, so I debugged the issue and proposed a fix in PR #56 

You'll want to take a look at the attached files in my original message and see the <track> embedded in another <track> to see the problem

**Comment by sbraz** [comment]
As I said, I can't do anything with those files because they are not the format that I expect. If sharing the files publicly is a problem, can you please email them to me? My email is present in all commits.
