### ISSUE TITLE
OSError when parsing

### ISSUE THREAD

**Issue by frischfrosch** [sbraz/pymediainfo#73]
Hi, 
I am on Fedora 31 using version 4.1 of pymediainfo and got this:
```
Traceback (most recent call last):
  File "/home/dau/PycharmProjects/Cutlister/Cutlister.py", line 135, in <module>
    cl = CutLister()
  File "/home/dau/PycharmProjects/Cutlister/Cutlister.py", line 26, in __init__
    self.get_mediainfo()
  File "/home/dau/PycharmProjects/Cutlister/Cutlister.py", line 41, in get_mediainfo
    media_info = pymediainfo.MediaInfo.parse(self.video_filename)
  File "/home/dau/.conda/envs/Cutlister/lib/python3.7/site-packages/pymediainfo/__init__.py", line 263, in parse
    lib, lib_version_str, lib_version = cls._get_library(library_file)
  File "/home/dau/.conda/envs/Cutlister/lib/python3.7/site-packages/pymediainfo/__init__.py", line 188, in _get_library
    lib = lib_type(library)
  File "/home/dau/.conda/envs/Cutlister/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
**OSError: /lib64/libssh.so.4: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b**
```

**Comment by sbraz** [comment]
How did you install pymediainfo and libmediainfo? It looks like your libmediainfo.so is broken and built for another version of OpenSSL.

**Comment by frischfrosch** [comment]
libmediainfo via dnf and pymediainfo via pycharm. mediainfo works on the shell

**Comment by sbraz** [comment]
Please try using Fedora's pymediainfo.

If this doesn't work, please add `print(library)` before line 188 of `/home/dau/.conda/envs/Cutlister/lib/python3.7/site-packages/pymediainfo/__init__.py` to see what library file it attempts to open, maybe it's not the one from the RPM?

**Comment by frischfrosch** [comment]
Fedora's pymediainfo works - thanks a lot!
